name: sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write   # 👈 gives GHA permission to push commits

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # use default token

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull remote changes
        run: git pull origin main --rebase

      - name: Push local changes
        run: |
          git add .
          git commit -m "sync changes" || echo "No changes to commit"
          git push origin main

      # ✅ Run Maven build & tests
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests
        run: mvn test

      # ✅ Upload Surefire Reports (JUnit/TestNG XMLs)
      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports/**


      - name: Upload Extent Reports
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: test-output/**
